Brenden
CIC-methods/FID-A pull request #36
Opened 2020-11-10 22:21 UTC by brendo-k

Created MRSI processing  package and built MRSI trajectory simulation

2020-11-11 01:04 UTC, gdevenyi commented
Hi @brendo-k can you rebase your branch on the latest master HEAD so that the commit history is clean?

2020-11-11 01:08 UTC, gdevenyi requested changes

2020-11-11 01:08 UTC, gdevenyi commented on MRSI Trajectory Simulation/Simulation/CreateTrajectory.m~
> +function [TrajectoryStruct] = CreateTrajectory(Trajectory, par)
Looks  like this file is an inappropriately committed backup copy?

2020-11-11 01:08 UTC, gdevenyi commented on MRSI Trajectory Simulation/Simulation/Rosette.m~
> +% Rosette.m
Here again a backup file

2020-11-11 01:08 UTC, gdevenyi commented on MRSI Trajectory Simulation/Simulation/cartMRSI.m~
> +function [traj, scanTime] = cartMRSI(par)
another backup file

2020-11-11 07:25 UTC, brendo-k commented
Hi @gdevenyi did I do the rebase correctly? I also deleted the backup files in the simulation file.

2020-11-11 19:04 UTC, jamienear commented
Thanks @brendo-k!  It looks good to my untrained eye.  I've attached a network graph showing that your branch seems to be rebased from the most recent commit on the master (07628be), so it seems right.  But I will wait to hear from @gdevenyi before I merge, in case there is something I'm missing.  

-Jamie

![Screen Shot 2020-11-11 at 13 59 23](https://user-images.githubusercontent.com/9385793/98853162-b8a35080-2426-11eb-9c50-8faf8e7b9fa4.png)

2020-11-11 19:38 UTC, gdevenyi commented
You can see in the commit history of this PR a large number of entries which are not authored by you but instead merges on master.

Please take a look at https://stackoverflow.com/questions/56708751/github-pull-requests-showing-more-and-more-old-merges

2020-11-11 21:13 UTC, brendo-k commented
Could a reason for the large number of commits be because this branch is behind master? I rebased my code to master and the made a PR to this branch.

2020-11-12 01:06 UTC, gdevenyi commented
> Could a reason for the large number of commits be because this branch is behind master?

That is what rebasing is supposed to fix.

2020-11-12 01:54 UTC, brendo-k commented
I'm a little confused. Can you help me figure out where I went wrong?
1. I made a new branch on my forked repository
2. I used `git rebase upstream master` on the new branch
3. I made a pull request from my branch to the csi_mod branch (which is 48 commits behind master)

2020-11-12 02:09 UTC, gdevenyi commented
Okay, sorry, I see the issue here. This PR is against FID-A/csi_mod, which is very very behind master. Your branch is based off master, so its pulling in all the updated commits.

Is that intentional, or should this PR be against master?

2020-11-12 02:23 UTC, brendo-k commented
Hi Gabe, 

No worries thanks for clearing it up! Yes, this is intentional, we didn't want to push it to master since this feature is still unfinished.

2020-11-12 03:23 UTC, jamienear commented
Sorry, I also didn't realize that this pull request was against the csi_mod branch.  Maybe I should rebase csi_mod to master before pulling in Brenden's changes?  This way it will no longer appear that I am pulling in so many updated commits.

2020-11-12 03:24 UTC, gdevenyi commented
@jamienear that would clear things up slightly, but its up to you :)

2020-11-12 18:11 UTC, jamienear commented
I just re-based the csi_mod branch to master.  @gdevenyi do you think I can safely merge the pull request now?

2020-11-12 18:12 UTC, jamienear commented
<img width="946" alt="Screen Shot 2020-11-12 at 13 12 05" src="https://user-images.githubusercontent.com/9385793/98978961-b4d80280-24e8-11eb-9931-2951ff145c07.png">

2020-11-12 18:16 UTC, gdevenyi commented
Looks good :+1:

2020-11-12 18:23 UTC, merged